version: '3.4'
services:
  db:
    image: onrefni/mysql-client-system
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: client_manage_schema
    ports:
      - "3308:3306"
    networks:
      - client-network
  client-system:
    image: onrefni/rest-client-system
    restart: always
    build: ./ClientSystem
    working_dir: /ClientSystem
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./ClientSystem:/ClientSystem
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - client-network
networks:
    client-network:
        driver: bridge
